version: '2.3'

services:
  app:
    image: app
    env_file: .env
    # runtime: nvidia
    pid: "bridge"
    ports:
      - 5017:5000
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    command: sh start_service.sh 

volumes:
  app: